# Will be run to create a zendesk ticket out of a issue
on:
  issues:
    types: [opened]
  workflow_call:
    secrets:
      ZENDESK_BASIC_AUTH:
        description: 'The zendesk basic auth token for authentification. See https://support.zendesk.com/hc/en-us/articles/115000510267-How-can-I-authenticate-API-requests-#heading2'
        required: true
jobs:
  issue_created:
    name: Issue created
    runs-on: ubuntu-latest
    steps:
      - env:
          ZENDESK_BASIC_AUTH: ${{ secrets.ZENDESK_BASIC_AUTH }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_USER: ${{ github.event.issue.user.login }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          ## create ticket in zendesk
          body=$(jq -n --arg body "$ISSUE_BODY" '{body: $body}' | jq .body)
          echo "$body"

          curl -X POST https://memsource.zendesk.com/api/v2/tickets -H "Authorization: Basic $ZENDESK_BASIC_AUTH" -H "Content-Type: application/json" --data-binary @- <<DATA
          {
            "ticket": {
              "subject":   "Github_Issue: $ISSUE_TITLE",
              "comment":   { "body": "[GITHUB_ISSUE_COMMENT]\n\n${body:1:-1}" },
              "assignee_id": 383200172360,
              "group_id": 360008131599,
              "brand_id": 360002503940,
              "tags": ["phrase"],
              "external_id": "$ISSUE_URL",
              "requester": { "locale_id": 1, "name": "$ISSUE_USER from Github", email: "$ISSUE_USER@users.noreply.github.com" }
            }
          }
          DATA

          echo "Zendesk ticket created"
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Our technical support team got notified and will get in touch with you."
            })

